### ISSUE TITLE
 AttributeError: __enter__

### ISSUE THREAD

**Issue by yaconsult** [Mikts/pbwrap#11]
`This module always worked perfectly for me in the past but I just tried to use it again and the error above is generated.  Perhaps it is due to changes made to python since the module was written?  I am using Python 3.9.5.

pb = Pastebin(api_dev_key)
user_id =pb.authenticate(username, password)

# This works fine!
paste_url = pb.create_paste('this is a test', api_paste_private=1, api_paste_name='test')
print(paste_url)

# When pasting a file, an I/O error is returned when it  tries to open the file
with open('test.txt', 'w') as f:
    f.write('This is line #1\n')
    f.write('This is line #2\n')

paste_url = pb.create_paste_from_file('test.txt', api_paste_private=1, api_paste_name='test')

# pbwrap.py", line 180, in create_paste_from_file
#     with io.open(
# AttributeError: __enter__

print(paste_url)
print('Done')`

**Comment by yaconsult** [comment]
This seems to be the commit that broke it by combining io.open, with, and read():
[https://github.com/Mikts/pbwrap/commit/c67ccca59096b5284c4c5f0080c96c0f20207113](url)

**Comment by yaconsult** [comment]
I created a pull request for a fix to the create_paste_from_file function.

**Comment by Mikts** [comment]
@yaconsult  hey nice catch maybe it has to do with some python version changes. I'll review the PR and merge it along with anythign that requires update for python 3.9.

**Comment by Mikts** [comment]
Closing this as this #12 fixes it. Thank you for the catch @yaconsult i released v1.3.0 which contains the fix!
