### ISSUE TITLE
self-signed cert causing invalid ssl cert error

### ISSUE THREAD

**Issue by lord-aceldama** [Mikts/pbwrap#9]
suggest option to verify ssl certs

HTTPSConnectionPool(host='pastebin.com', port=443): Max retries exceeded with url: /api/api_login.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

**Comment by Mikts** [comment]
Can you explain a bit more? It worked as it should if Pastebin had a certificate issue.

**Comment by lord-aceldama** [comment]
Certain firewall or antivirus solutions replace the pastebin cert with a
self-signed cert. In this instance, the culprit was Kaspersky. As i
mentioned, it would be nice to have the option to disable ssl cert
checking. Easiest implementation i can think of would be by means of kwarg
expansion. [ ie. func(param, param, **kwarg)]

**Comment by Mikts** [comment]
Ah now i see what you mean. Yeah it's a nice idea i can expose the option :smile_cat:

**Comment by Mikts** [comment]
Closing it as #10 fixes this.
